# The URL the site will be built for
base_url = "https://3tilley.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Generate an atom/rss feed
generate_feed = true

theme = "papermod"

taxonomies = [
  { name = "tags", feed = true }
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
google_analytics = "G-W8MM0ES7PC"

[extra.papermod]
title = "TheTraitModern"
default_theme = "auto"
theme = "light"
language_direction = "auto"
keywords = ["rust", "python"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = false
show_post_nav_links = true
show_post_meta = true
default_toc_open = true
show_post_edit_button = true
edit_post_url = "https://github.com/3tilley/3tilley.github.io/tree/master"
#copyright = ""
date_format = "%Y-%m-%d"
navigation = [
  { url = "$BASE_URL/archive", title = "Archive" },
  { url = "$BASE_URL/tags", title = "Tags" },
  { url = "https://getzola.org/", title = "Zola", is_external = true }
]

home_title = "The Trait Modern"
home_content = "Musings on Rust, and maybe some Python"
social_icons = [
  { url = "https://github.com/3tilley", title = "GitHub", icon = "github" },
]
